
kafka:
  topic: test5
spring:
  kafka:
    bootstrap-servers: kafka1:9091,kafka2:9092,kafka3:9093
    admin:
      client-id: local
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: local
    streams:
      application-id: stream-app
      client-id: stream-client


