
kafka:
  topic: test2
spring:
  kafka:
    admin:
      client-id: client

    producer:
      bootstrap-servers: kubernetes.docker.internal:9092
    consumer:
      bootstrap-servers: kubernetes.docker.internal:9092
    bootstrap-servers: kubernetes.docker.internal:9092


